modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL = "https://github.com/Hunter19823/Borealis/issues"
license = "All Rights Reserved"

[[mods]]
modId="borealis"
version="${file.jarVersion}"
displayName="Borealis"
authors="ILIKEPIEFOO2"
description='''
An updated version of the 1.12.2 mod Aurora specifically
designed to provide documentation for kubejs.
(Seriously though credit goes to Latvian Modder aka
the author of both Aurora and KubeJS)
'''

[[dependencies.borealis]]
modId="forge"
mandatory = true
versionRange = "[33,)"
ordering = "NONE"
side="BOTH"

[[dependencies.borealis]]
modId="kubejs"
mandatory = false
versionRange = "[1603,)"
ordering = "AFTER"
side="BOTH"

[[dependencies.ftbquests]]
modId="ftbquests"
mandatory = false
versionRange = "[1604,)"
ordering = "AFTER"
side="BOTH"